github: [Repository metadata]
timezone: Europe/Bratislava

author: "Juraj Fiala"
email: "doctorjellyface@riseup.net"
nick: "Doctor Jellyface"

gems:
    - jekyll-feed
    - jekyll-sitemap

defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:categories/:year/:month/:day/:title/

theme: jekyll-theme-minimal