# Site settings
title:       Ramblings
description: On life and such
url:         "https://fjalla.tk"

# Personal info
author: Juraj Fiala
email:  jurf@riseup.net

# Other accounts
twitter_username: eurai_fjalla
github_username:  jurf
disqus:
  shortname:      doctorjellyface # Cannot be changed

# Build settings
timezone:  Europe/Bratislava
permalink: pretty
theme:     minima
markdown:  CommonMarkGhPages
commonmark:
  options: ["SMART", "STRIKETHROUGH_DOUBLE_TILDE"]
  extensions: ["strikethrough", "autolink"]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
