timezone: Europe/Bratislava
title: Juraj Fiala
description: Welcome, to my very own internet ~/

author: Juraj Fiala
email: doctorjellyface@riseup.net
twitter_username: DoctorJellyface
github_username: DoctorJellyface
disqus:
  shortname: doctorjellyface

gems:
    - jekyll-feed
    - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:categories/:year/:month/:day/:title/

# Build settings
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
