# Site settings
title:       Juraj Fiala
description: Welcome, to my very own internet ~/

# Personal info
author: Juraj Fiala
email:  doctorjellyface@riseup.net

# Other accounts
twitter_username: DoctorJellyface
github_username:  DoctorJellyface
disqus:
  shortname:      doctorjellyface

# Build settings
timezone:  Europe/Bratislava
permalink: pretty
theme:     minima

gems:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
