# Site settings
title:       Juraj Fiala
description: My very own little internet ~/

# Personal info
author: Juraj Fiala
email:  jurf@riseup.net

# Other accounts
twitter_username: eurai_fjalla
github_username:  jurf
disqus:
  shortname:      doctorjellyface # Cannot be changed

# Build settings
timezone:  Europe/Bratislava
permalink: pretty
theme:     minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
